export const CHAT_BAD_REQUEST_ERRORS = {
    INVALID_CHAT_REQUEST_BODY:'INVALID_CHAT_REQUEST_BODY',
    CHAT_UNEXPECTED_ERROR:CHAT_BAD_REQUEST_ERRORS.CHAT_UNEXPECTED_ERROR,
    CHAT_NOT_FOUND:'CHAT_NOT_FOUND',
    USER_ALREADY_IN_GROUP:'USER_ALREADY_IN_GROUP',
    GROUP_CHAT_ALREADY_EXISTS:'GROUP_CHAT_ALREADY_EXISTS'
}