name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.11.1
          registry-url: https://npm.pkg.github.com/
          scope: '@suryac72'

      - run: npm install --legacy-peer-deps
        env:
          NX_TOKEN: ${{secrets.NX_TOKEN}}